spring.application.name=crm

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=${NEO4J_PASSWORD}

jwt.secret-key=moj-bardzo-tajny-klucz-ktory-ma-przynajmniej-32-znaki-dlugosci
jwt.expiration=86400000

